### ISSUE TITLE
v0.14

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#1209]
#### Todo list for this version:
- [x] MetroWindow Opacity Not Working #1366 (make a overriding property)

---
- [x] Push v0.13.x #925 
- [x] Document more controls - #944 
- [x] Inactive Window Color #1163 PR #1320 
- [x] ScrollBars too narrow #1019 PR Extracted ScrollBar Width/height #1387 

---
#### Other Changes:
- [ ] Make MA.M more MVVM-friendly #999 
- [x] FlipView v2 #1040 
- [x] PasswordBox watermark visible even if password set #1343 PR #1353 
- [x] Flyout problem with width bound to ancestor's ActualWidth #1339 PR #1368 
- [x] ComboBox HorizontalContentAlignment Not Working #1367 PR #1369 
- [x] ComboBox ClearTextButton bug #1338 PR #1370 
- [x] some TextboxHelper issues: TextboxHelper.ClearTextButton does not work when is applied via Trigger #1283 PR #1371 
- [x] ShowMinButton="False" and ShowMaxRestoreButton="False" not working #1362 PR #1376 
- [x] Flyouts not visible in designer #1378 PR #1379 
- [x] DataGrid Issue - Highlight Color misaligns when RowHeight is not default value #848 PR #1381 
- [x] updated TextboxHelper.Watermark to respect Textbox Padding #1247 
- [x] MetroFlatButton moved to Buttons resource dictionary Controls.Button.xaml #1210 PR #1384 
- [x] Add new LoginDialog control and demo PR #1276 #1390 
- [x] DataGrid Cell Padding not being applied #977 PR #1393 
- [x] ComboBox has Virtualizing disabled #1132 PR #1394 
- [x] Scrolling is broken when grouping is used in a ComboBox #1309 PR #1395 
- [x] Dialogs crash when app style is set via ThemeManager #1358 and How to use ShowMessageAsync()? #1385 PR #1383 
- [x] simplify MetroButton and MetroToggleButton style (sometime we got a blurry border) #1397 
- [x] [Fix] Row is always of constant height: #1399 -> Set MinRowHeight instead of RowHeight of MetroDataGrid
- [x] Enable text wrapping in ToggleSwitch Header #1415 
- [x] titlebar enhancement etc... #1414 
- [x] MetroWindow GlowBrush remains when hiding window #1422 #1403 PR #1424 
- [x] Problem with the Calendar control #1133 PR #1426 
- [x] Support runtime accents #1430 
- [x] DataGrid selection mode to cell doesn't work #975 PR #1446 
- [x] fix selection with SelectionUnit=CellOrRowHeader PR #1452 
- [x] Custom style for TreeView not performing #1444 PR #1450 
- [x] Minimize, Maximize buttons can have focus #1472 PR #1475 

---
#### Attention
- some changes for system menu: menu is shown on
  - icon
  - if mouse yPos <= TitlebarHeight
  - if UseNoneWindowStyle = true
- `MetroWindow` has two new dependency properties
  - `ShowSystemMenuOnRightClick` default to `true`
  - `ShowWindowButtonCommandsOnHiddenTitleBar` default to `true`

---
