### ISSUE TITLE
Version 0.11.0

### ISSUE THREAD

**Issue by shiftkey** [MahApps/MahApps.Metro#322]
Before I push a new stable release I want to close out these high-severity bugs and pull requests
- [x] flickering after 'Basic concept of glow window from GitHub project' - #419 
- [x] Weird behaviour when ContextMenu open - #465 
- [x] Datepicker respects fontsize - #471 
- [x] Calendar and DarkTheme - #470 
- [x] Use Microsoft.Windows.Shell instead of hand-coded solution for WinForms interop - #503
