### ISSUE TITLE
v0.11.3.1

### ISSUE THREAD

**Issue by AzureKitsune** [MahApps/MahApps.Metro#744]
Things that need to be dealt with before 0.11.3.1.
(Yes, I know this should be a milestone instead of an issue but this looks nicer).
- [x] Fix assembly version: see #733 
- [x] if a TextBox becomes multiline and it was resized, the ScrollBar goes
  away 516b5bc55b6e46b395042a19c482a875dcdc4373
- [x] at GlowWindow: PresentationCore Value cannot be null #752 395ae447383f01c4f7139715e4409e12b7699016 ( @punker76 )
- [x] open Flyouts should change their accent color too, minor improvement to ThemeManger (ThemeChanged event...), fix context menu with dark theme #746 ( @punker76 )
- [x] improve menu / context menu style, the current is ugly #745 #749 ( @punker76 )
- [x] #761 thememanager warnings blablubb ( @punker76 )
- [x] Begin documenting code ( @Amrykid ) - See PR #748 and #753 
- [x] New Flyout animation. ( @Amrykid ) - See PR #747 
- [x] Fix #757 ( @Amrykid ) - See PR #758
- [x] #658 ToggleSwitch state incorrect if not visible ( @punker76 )
- [x] TabControl / TabItem / MetroTabItem issues #566 #627 #551 ( @punker76 )
- [x] SquareButton: colors in flyout #705 ( @punker76 ) 
- [x] WindowStyle.None in MetroWindow #717 see PR #779 
- [x] minor Glow Window changes (with main window animation glow window sucks) ( @punker76 ) - See PR #787 
- [x] minor update to default Slider styles, should we use the flat design as default? -> no, users can decide what they want. PR #791 
- [x] rewrite/improve/introduce MahApps.Metro ShowMessage ( @Amrykid ) - See #696 and PR #764 - Check out #550 for @stefan-schweiger 's take and #657 for @DharmeshPatel33 's take
- [x] fix / improve validation error #682 #677 #589 #71 ( @punker76 ) See PR #798 
- [x] We also need to deal with #322 
  - [x] Release Notes to document new features and breaking changes
  - [x] Update site notes to indicate Microsoft.Windows.Shell is consumed by .NET4 version
