### ISSUE TITLE
v0.12.0

### ISSUE THREAD

**Issue by AzureKitsune** [MahApps/MahApps.Metro#800]
Todo list for this version:
- [x] Push v0.11.3.1 [**MANDATORY**] - #744
- [x] Push upgraded dialog mechanics [MetroDialogs v2] - #785 (@Amrykid)
- [x] Push MetroDialogs v3 - #860 (@Amrykid)
- [x] Push MetroDialogs v4 - #901 (@Amrykid)
- [x] Fix MetroProgressBar IsIndeterminate issue - see #817 (thanks @spiritdead)
- [x] Implement ContentTemplateSelector support into the TransitioningContentControl - #754 (@Amrykid) -> #876 
- [x] Implement MetroNavigationWindow (@Amrykid) - #789, see PR #801
- [x] Remove ProgressIndicator, MetroImage and Panorama (@flagbug) - PR #939 
- [x] Trouble with GlowBrush with Windows when hide/show #839 (@punker76) See PR #843
- [x] Implement Flyout Themes #836 - Maybe set the Flyout's theme to the opposite of it's parent MetroWindow. (@flagbug) - see PR #941 
- [x] CleanWindow: Using GlowBrush property enables the resizing of the window. #851 (@Amrykid ) see PR #896 
- [x] ShowWindowCommandsOnTop="False" doesn't work for CleanWindowStyle. #894 (@Amrykid) see PR #896
- [x] ToggleSwitch has "integrated" Top/Left Margin (#878 ) - See PR #880 (@Amrykid)
- [x] Window can't be dragged down from the topmost pixel when maximized - #921  (@flagbug)
- [x] Update release notes when its all said and done: https://github.com/MahApps/MahApps.Metro/blob/master/docs/release-notes/0.12.0.md

Other changes:
- "AccentedSquareButton, IdealForegroundColor key and hover-effect for Dialog buttons." - #845
- "Removed title parameter from ShowMetroDialogAsync" - #842 (thanks @thoemmi)
- "BaseMetroDialog._WaitForCloseAsync crashes" - #945 (thanks @thoemmi)
- "Add Numericupdown Control to MahApps.Metro" - #841 and implemented in #846 (thanks @xxMUROxx).
  - "[RFC] NumericUpDown" - #899
  - "NumericUpDown: Value Property has not set BindsTwoWayByDefault" - #927 
  - [HOTFIX] NumericUpDown SpeedUp is now properly working again. - #931 
- "fix copy&paste memory leak at CustomValidationPopup" - #907 
- "Fixes #874" - #917 (thanks @h1srf)
- Dialogs: "Window SizeToContent"/"Optional sizetocontent" - #881 and PR #882 (thanks @Icehunter).
- "Added appbar_more_horizontal/vertical" #887 (thanks @Dotnetifier)
- "ThemeManager's OnThemeChanged work-around conflicting with other WPF internals." - #923 - #932 (thanks @remcoros)
- "Fix build madness" #929 (thanks @flagbug)
