### ISSUE TITLE
0.12.1

### ISSUE THREAD

**Issue by flagbug** [MahApps/MahApps.Metro#956]
Before we release 0.13, we should put out a bug-fix release containing some fixes for my oversights, a performance fix, the fix for the cleanwindow style and any other glaring bugs that are show-stoppers
- [x] Fix WindowCommand brushes when using Flyouts #949 
- [x] Overflow Exception fix in the Clean Window #903
- [x] Commit https://github.com/MahApps/MahApps.Metro/commit/c60df76e16d16ad8d665f5c791a6c8809cdd6045
- [x] Fix for NumericUpDown Exception raised when trying to enter a number in scientific notation #953 
- [x] WindowCommands are white by default in the CleanWindowDemo #990 
- [x] Flyouts need to respond to the "Theme" setter #972 
- [x] ControlTemplate did not respect Flyout's Margin #974

Any others?
